name: Build Docs

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
    
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
          --from markdown
          --to docx
          --embed-resources
          --reference-doc .\Docs\_template.docx
          --resource-path=.\Docs\Description\
          -s .\Docs\Description\README.md
          -o Description.docx
          
      - uses: actions/upload-artifact@v3
        with:
        name: my-artifact
        path: Description.docx