name: Build Docs

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
    
      - run: cd ./Docs/Description/
    
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            --from markdown
            --to docx
            --reference-doc _template.docx
            --resource-path=./
            -s README.md
            -o Description.docx
          
      - uses: actions/upload-artifact@v3
        with:
          name: Description
          path: Description.docx